//
//  HomeTileList.swift
//  StatsScanner
//
//  Created by Kamran on 12/31/21.
//

import Foundation
import UIKit

/// Data structure that enumerates the elements of each tile. Allows each tile to have a centralized, editable structure.
/// - Parameters:
///     - dataSetImage: Icon image as a ``UIImage`` for the dataset tile that will be displayed on the home screen
///     - dataSetName: ``String`` type for the name of the dataset
///     - creationDate: Autogenerated ``String`` for the 
struct tileList {
    let dataSetImage: UIImage
    let dataSetName: String
    let creationDate: String
    let numItems: String
}
