# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/Library/Caches/actions/xcodebuild
          key: ${{ runner.os }}-${{ hashFiles('**/Podfile.lock') }}

      - name: Build and Test
        run: |
          xcodebuild build -workspace StatScanner.xcworkspace -scheme StatScanner -destination "platform=iOS Simulator,name=iPhone 13" -configuration Release
          xcodebuild test -workspace StatScanner.xcworkspace -scheme StatScanner -destination "platform=iOS Simulator,name=iPhone 13"

